# Generated by Django 5.2 on 2025-04-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BitforceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actividad',
            new_name='Activity',
        ),
        migrations.RenameModel(
            old_name='Sucursal',
            new_name='Branch',
        ),
        migrations.RenameModel(
            old_name='Turno',
            new_name='Shift',
        ),
    ]
