# Generated by Django 5.2 on 2025-10-07 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BitforceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('nombre', 'direccion')},
        ),
    ]
