# Generated by Django 5.2 on 2025-10-09 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BitforceApp', '0002_alter_branch_options_alter_branch_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-fecha_hora']},
        ),
        migrations.AddField(
            model_name='activity',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='cutoff_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Minutos antes del inicio en que se cierra la inscripción'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(help_text='Cupo máximo por horario'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BitforceApp.coach'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duracion',
            field=models.PositiveIntegerField(help_text='Duración en minutos'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['nombre'], name='BitforceApp_nombre_e941c4_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activo'], name='BitforceApp_activo_c27aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['actividad', 'sucursal', 'fecha_hora'], name='BitforceApp_activid_fdab3c_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['gymuser', 'fecha_hora'], name='BitforceApp_gymuser_8f70ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('gymuser', 'actividad', 'sucursal', 'fecha_hora'), name='unique_booking_per_user_per_slot'),
        ),
    ]
