# Generated by Django 5.2 on 2025-04-22 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountAdmin', '0002_remove_gymuser_address_remove_gymuser_nombre_and_more'),
        ('BitforceApp', '0002_rename_actividad_activity_rename_sucursal_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='gymuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountAdmin.gymuser'),
        ),
        migrations.DeleteModel(
            name='GymUser',
        ),
    ]
