# Generated by Django 5.2 on 2025-04-30 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BitforceApp', '0003_alter_shift_gymuser_delete_gymuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='GymUser',
        ),
        migrations.AlterField(
            model_name='shift',
            name='gymuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GymUser',
        ),
    ]
