# Generated by Django 5.2 on 2025-10-14 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BitforceApp', '0003_alter_activity_options_alter_shift_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bitforceapp_booking',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ClaseProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('capacidad', models.PositiveIntegerField(help_text='Cupo del slot (default: actividad.capacidad_maxima)')),
                ('cutoff_minutes', models.PositiveIntegerField(blank=True, help_text='Override; si es null usa el de la actividad', null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['inicio'],
            },
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['nombre', 'direccion']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'managed': False, 'ordering': ['-creado']},
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='BitforceApp_nombre_e941c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='BitforceApp_activo_c27aeb_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claseprogramada',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='BitforceApp.activity'),
        ),
        migrations.AddField(
            model_name='claseprogramada',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BitforceApp.coach'),
        ),
        migrations.AddField(
            model_name='claseprogramada',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='BitforceApp.branch'),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='BitforceApp.claseprogramada'),
        ),
        migrations.AddIndex(
            model_name='claseprogramada',
            index=models.Index(fields=['actividad', 'sucursal', 'inicio'], name='BitforceApp_activid_4faf11_idx'),
        ),
        migrations.AddIndex(
            model_name='claseprogramada',
            index=models.Index(fields=['inicio'], name='BitforceApp_inicio_3141ff_idx'),
        ),
        migrations.AddIndex(
            model_name='claseprogramada',
            index=models.Index(fields=['activo'], name='BitforceApp_activo_66d1a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='claseprogramada',
            unique_together={('actividad', 'sucursal', 'inicio')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['slot'], name='bitforceapp_slot_id_7d8aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user'], name='bitforceapp_user_id_1c2145_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('user', 'slot'), name='unique_booking_per_user_per_slot_new'),
        ),
    ]
