# Generated by Django 5.2 on 2025-10-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BitforceApp', '0004_booking_claseprogramada_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
