# Generated by Django 5.2 on 2025-04-22 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountAdmin', '0001_initial'),
        ('BitforceApp', '0002_rename_actividad_activity_rename_sucursal_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='gymuser',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='gymuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='gymuser',
            name='Branch',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='BitforceApp.branch'),
        ),
        migrations.AddField(
            model_name='gymuser',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
        migrations.AddField(
            model_name='gymuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('limMerchant', 'Limitado')], default='limMerchant', max_length=20),
        ),
    ]
