# Generated by Django 5.2 on 2025-10-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymuser',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
