# Generated by Django 5.2 on 2025-10-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountAdmin', '0002_alter_gymuser_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gymuser',
            name='creditos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gymuser',
            name='fecha_activacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymuser',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
