# Generated by Django 5.2 on 2025-04-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountAdmin', '0002_remove_gymuser_address_remove_gymuser_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymuser',
            name='Branch',
            field=models.CharField(default='', max_length=100),
        ),
    ]
